# data
img_size: 32
in_chans: 3
num_classes: 100
batch_size: 128
num_workers: 4
# model
patch_size: 4
embed_dim: 192
num_blocks: 12
num_heads: 3
mlp_ratio: 4.0
drop_rate: 0.1
attn_drop: 0.1
drop_res: 0.2
# train
epochs: 100
lr: 0.0005
weight_decay: 0.05
grad_clip: 1.0
man_grad_clip: 1.0
amp: true
hamp: false
seed: 42
init_cls_scale: 0.3
hyp_init_c: 1.0
hyp_init_s: 1.0
t: 0.985 
proto_std: 0.02
# dir
out_dir: checkpoints

